language: rust
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly
notifications:
  irc:
    channels:
      - "chat.freenode.net##crisidev"
    on_success: always # default: always
    on_failure: always # default: always
    use_notice: true
