language: rust
cache: cargo
script:
  - git submodule update --init --recursive
  - cargo build --verbose --all
  - cargo test --verbose --all
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
notifications:
  irc:
    channels:
      - "chat.freenode.net##crisidev"
    on_success: always # default: always
    on_failure: always # default: always
    use_notice: true
